use_frameworks!

platform :ios, '9.0'

target 'HQYPlayer_Example' do
  pod 'HQYPlayer', :path => '../'

  target 'HQYPlayer_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
