#use_frameworks!

platform :ios, '9.0'

target 'HQYPlayer_Example' do
  pod 'HQYPlayer/TXLiteAVSDK_Professional', :path => '../'
#  pod 'IJKMediaFramework'
#  pod 'HQYPlayer/TXLiteAVSDK_Professional'
end
